# Includes one of the default files in src/bootstrap/defaults

# MGH: Set build profile to build all of Rust ("user"), not just "tools", or
# else cargo doc will complain about a rustc version mismatch. rustdoc and rustc
# really need to be on the same version to build docs for an external module.
profile = "user"

# MGH: What does this do?
changelog-seen = 2

[rust]
# MGH: Enable debug and trace for everything
debug-logging = true
# This gets rid of the following warning:
# warning: some trace filter directives would enable traces that are disabled
# statically
# `rustdoc::passes::collect_intra_doc_links=trace` would enable the TRACE level
# for the `rustdoc::passes::collect_intra_doc_links` target
